=== TheSmartBeaver/DPR/master.dtd
<!-- DTD created at Sat Feb 29 12:22:06 CET 2020 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT  tag (#PCDATA)>
<!ATTLIST tag  attribute CDATA #REQUIRED>

<!ELEMENT  masterInformatique    (listeIntervenants, parcours+, listeUE, semestre+)>
<!ELEMENT  ue  		(nom, nbcredit, resume?, plan?, lieu?, refintervenant)>

<!ELEMENT   nom  	        (#PCDATA)>
<!ELEMENT   identifiant     (#PCDATA)>
<!ELEMENT   nbcredit 	    (#PCDATA)>
<!ELEMENT   resume  	    (description)>
<!ELEMENT   plan  	        (#PCDATA)>
<!ELEMENT   lieu  	        (#PCDATA)>

<!ELEMENT   intervenant     (identifiant, nom, mail, site)>
<!ELEMENT   mail            (#PCDATA)>
<!ELEMENT   site          	(#PCDATA)>

<!-- Des entités internes permettant de générer adresses -->
<!ENTITY    dom.lislab    "@lis-lab.fr" >
<!ENTITY    dom.amuHost      "@univ-amu.fr" >
<!ENTITY    dom.persoHost     "perso.luminy&dom.amuHost;" >

<!--Possibilité d'ajouté une difficulté en attribut de "ue" -->
<!ENTITY % difficulte "difficul (facile|moyen|difficile) #IMPLIED">
<!ATTLIST ue %difficulte;>
<!ATTLIST ue    id  ID #REQUIRED>

<!ELEMENT   listeIntervenants   (intervenant+) >
<!ATTLIST   intervenant  id  ID  #REQUIRED>
<!ELEMENT   refintervenant   EMPTY>
<!ATTLIST   refintervenant  ref IDREF  #IMPLIED>

<!ELEMENT   parcours        (nom, listeResponsables, description, listeDebouches,ref-semestre+)>
<!ELEMENT   listeResponsables   (responsable+)>
<!ELEMENT   responsable         (#PCDATA)>
<!ELEMENT   listeUE             (ue+)>

<!ELEMENT   listeDebouches      (metier+)>
<!ELEMENT   metier              (#PCDATA)>

<!ELEMENT   semestre            (bloc+)>
<!ATTLIST   semestre    id ID #REQUIRED>

<!ELEMENT   bloc                (ref-ue+, role)>
<!ELEMENT   role                (#PCDATA)>


<!ELEMENT   ref-ue              EMPTY>
<!ATTLIST   ref-ue          ref IDREF #REQUIRED>
<!ELEMENT   ref-semestre        EMPTY>
<!ATTLIST   ref-semestre    ref IDREF #REQUIRED>

<!--Description usant d'un contenu mixte -->
<!ELEMENT description (#PCDATA|paragraphe|tab|liste-pucee)*>

<!ELEMENT paragraphe (#PCDATA|gras|link|italique)*>
<!ELEMENT tab (tabLine+)>
<!ELEMENT liste-pucee (paragraphe+)>

<!ELEMENT gras (#PCDATA)>
<!ELEMENT italique (#PCDATA)>
<!ELEMENT link (#PCDATA)>

<!ELEMENT tabLine (tab-element+)>
<!ELEMENT tab-element (#PCDATA)>

=== TheSmartBeaver/DPR/master.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Sat Feb 29 12:19:18 CET 2020 -->

<!DOCTYPE masterInformatique SYSTEM "master.dtd">

<!--<masterInformatique
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="masterILD.xsd"> -->

<masterInformatique>
    <listeIntervenants>
        <intervenant id="Rem">
            <identifiant>Rem</identifiant>
            <nom>Morin Remi</nom>
            <mail>remiMorin@lis-lab.fr</mail>
            <site>remiMorin.perso.luminy@univ-amu.fr</site>
        </intervenant>

        <intervenant id="JL">
            <identifiant>Jean_Luc</identifiant>
            <nom>Jean Luc Massat</nom>
            <mail>jeanLucMassat@lis-lab.fr</mail>
            <site>jeanLucMassat.perso.luminy@univ-amu.fr</site>
        </intervenant>

        <intervenant id="EG">
            <identifiant>"Emm_G"</identifiant>
            <nom>Emmanuel Godard</nom>
            <mail>emmanuelGodard@lis-lab.fr</mail>
            <site>emmanuelGodard.perso.luminy@univ-amu.fr</site>
        </intervenant>

        <intervenant id="Nono">
            <identifiant>Noel_No</identifiant>
            <nom>Noël Novelli</nom>
            <mail>noelNovelli@lis-lab.fr</mail>
            <site>noelNovelli.perso.luminy@univ-amu.fr</site>
        </intervenant>


    </listeIntervenants>
    <parcours>
        <nom>ILD Ingénierie du logiciel et des données</nom>
        <listeResponsables>
            <responsable>Jean-Luc Massat</responsable>
            <responsable>Sana SELLAMI</responsable>
        </listeResponsables>
        <description>
            <paragraphe>L'objectif de ce parcours est de former des informaticiens qui soient capables à la fois de
                travailler
            </paragraphe>
            <paragraphe>sur les problématiques du <gras>développement logiciel</gras> (spécification, conception, réalisation,
                qualité, tests, plateforme JEE et WEB)
            </paragraphe>
            <paragraphe>et sur les problématiques de la <gras>modélisation et du traitement de données</gras> (administration,
                stockage, intégration, visualisation, analyse).
            </paragraphe>

            <paragraphe>Les points positifs de la formation :</paragraphe>
            <liste-pucee>
                <paragraphe>pas trop de maths mais quand même</paragraphe>
                <paragraphe>apprentissage des tests logiciels pour des applis robustes</paragraphe>
                <paragraphe>Cette formation est <gras>super</gras> avec  <italique>des profs de folie</italique>
                </paragraphe>
                <paragraphe>Plus d'info sur les bénéfices de la formation sur
                    <link>plusdinfololgg.univ-amu.fr</link>
                </paragraphe>
            </liste-pucee>
            <tab>
                <tabLine>
                    <tab-element>M1 Info ILD</tab-element>
                    <tab-element>M2 Info ILD</tab-element>
                </tabLine>
                <tabLine>
                    <tab-element>Des UEs communes à d'autres parcours et d'autres spécialisés ILD</tab-element>
                    <tab-element>Uniquement des UEs spécialisés ILD</tab-element>
                </tabLine>
            </tab>
        </description>
        <listeDebouches>
            <metier>Développeur</metier>
            <metier>Ingénieur</metier>
            <metier>Assistant ingénieur</metier>
            <metier>Architecte logiciel</metier>
        </listeDebouches>
        <ref-semestre ref="S1"/>
        <ref-semestre ref="S2ILD"/>
        <ref-semestre ref="S3ILD"/>
    </parcours>

    <parcours>
        <nom>FSI Fiabilité et sécurité informatique</nom>
        <listeResponsables>
            <responsable>Emmanuel Godard</responsable>
        </listeResponsables>
        <description>
            <paragraphe>La formation permet d’acquérir les principes et techniques liés à la conception,
                l’implémentation, l’exploitation de systèmes et applications informatiques
            </paragraphe>
            <paragraphe>sûrs dans un environnement ouvert et hétérogène. Les métiers visés sont ceux du large champ de
                la sécurité informatique (applications sécurisées,
            </paragraphe>
            <paragraphe>management de la sécurité, administration d’infrastructures, normes et qualité, audit de
                sécurité, R&amp;D).
            </paragraphe>
            <paragraphe>La formation apporte des <gras>compétences fortes en sécurité et fiabilité des applications</gras> (web,
                mobiles, embarquées), en sécurité organisationnelle, en sécurité des réseaux,
            </paragraphe>
            <paragraphe>en hacking éthique, en protocoles et architectures cryptographiques, en méthodes formelles.
                <italique>L’accent est mis sur le travail en équipe, sur des projets concrets</italique>,
            </paragraphe>
            <paragraphe>bénéficiant de l’apport des professionnels intervenant dans la formation.</paragraphe>
        </description>
        <listeDebouches>
            <metier>Ingénieur R&amp;D, Chargé de veille ou de recherche, Enseignant-chercheur ou chercheur</metier>
            <metier>Responsable de la sécurité des SI</metier>
            <metier>Ingénieur test et validation</metier>
            <metier>Responsable qualité</metier>
            <metier>Consultant technique ou fonctionnel</metier>

        </listeDebouches>
        <ref-semestre ref="S1"/>
    </parcours>

    <listeUE>
    <ue id="Res">
        <nom>Reseaux</nom>
        <nbcredit>4</nbcredit>
        <lieu>Luminy;St-Jerôme;St-Charles</lieu>
        <refintervenant ref="EG"/>
    </ue>
    <ue id="POC">
        <nom>Programmation Objet Concurrente</nom>
        <nbcredit>3</nbcredit>
        <lieu>Luminy;St-Jerôme;St-Charles</lieu>
        <refintervenant ref="Rem"/>
    </ue>
        <ue id="DPR">
            <nom>Donnees P-R</nom>
            <nbcredit>3</nbcredit>
            <resume><description>
                <paragraphe>Etude de XML, XSL, DTD, Schéma W3C, XQuery</paragraphe>
                <paragraphe><gras>Pour un même XML, plusieurs mise en forme possible</gras></paragraphe>
            </description></resume>
            <refintervenant ref="JL"/>
        </ue>
        <ue id="Secur">
            <nom>Sécurité des applications</nom>
            <nbcredit>6</nbcredit>
            <refintervenant ref="JL"/>
        </ue>
        <ue id="cryp">
            <nom>Cryptographie</nom>
            <nbcredit>3</nbcredit>
            <refintervenant ref="Rem"/>
        </ue>
        <ue id="ihm">
            <nom>Interface Homme Machine</nom>
            <nbcredit>3</nbcredit>
            <refintervenant ref="Nono"/>
        </ue>
        <ue id="BigD">
            <nom>Big Data</nom>
            <nbcredit>6</nbcredit>
            <refintervenant ref="Nono"/>
        </ue>
        <ue id="GL2">
            <nom>Génie Logiciel 2</nom>
            <nbcredit>6</nbcredit>
            <refintervenant ref="JL"/>
        </ue>
    </listeUE>

    <semestre id="S1">
        <bloc>
            <ref-ue ref="Res"/>
            <ref-ue ref="POC"/>
            <role>UEs Obligatoires</role>
        </bloc>
    </semestre>

    <semestre id="S2ILD">
        <bloc>
            <ref-ue ref="DPR"/>
            <ref-ue ref="Secur"/>
            <role>UE obligatoires pour le parcours ILD</role>
        </bloc>
        <bloc>
            <ref-ue ref="ihm"/>
            <ref-ue ref="cryp"/>
            <role>options à choisir</role>
        </bloc>
    </semestre>

    <semestre id="S3ILD">
        <bloc>
            <ref-ue ref="BigD"/>
            <ref-ue ref="GL2"/>
            <role>UEs obligatoires</role>
        </bloc>
    </semestre>


</masterInformatique>
