=== TheSmartBeaver/DPR/masterILD.dtd
<!-- DTD created at Sat Feb 29 12:22:06 CET 2020 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT  tag (#PCDATA)>
<!ATTLIST tag  attribute CDATA #REQUIRED>

<!ELEMENT  masterInformatique    (listeIntervenants, parcours+, semestre+)>
<!ELEMENT  ue  		(nom, identifiant, nbcredit, resume?, plan?, lieu?, refintervenant)>

<!ELEMENT   nom  	        (#PCDATA)>
<!ELEMENT   identifiant     (#PCDATA)>
<!ELEMENT   nbcredit 	    (#PCDATA)>
<!ELEMENT   resume  	    (#PCDATA)>
<!ELEMENT   plan  	        (#PCDATA)>
<!ELEMENT   lieu  	        (#PCDATA)>

<!ELEMENT   intervenant     (identifiant, nom, mail, site)>
<!ELEMENT   mail            (#PCDATA)>
<!ELEMENT   site          	(#PCDATA)>

<!-- Des entités internes permettant de générer adresses -->
<!ENTITY    dom.lislab    "@lis-lab.fr" >
<!ENTITY    dom.amuHost      "@univ-amu.fr" >
<!ENTITY    dom.persoHost     "perso.luminy&dom.amuHost;" >

<!--Possibilité d'ajouté une difficulté en attribut de "ue" -->
<!ENTITY % difficulte "difficul (facile|moyen|difficile) #IMPLIED">
<!ATTLIST ue %difficulte;>

<!ELEMENT   listeIntervenants   (intervenant+) >
<!ATTLIST   intervenant  id  ID  #IMPLIED>
<!ELEMENT   refintervenant   EMPTY>
<!ATTLIST   refintervenant  ref IDREF  #IMPLIED>

<!ELEMENT   parcours        (nom, listeResponsables, description, listeDebouches,ref-semestre+)>
<!ELEMENT   listeResponsables   (responsable+)>
<!ELEMENT   responsable         (#PCDATA)>

<!ELEMENT   listeDebouches      (metier+)>
<!ELEMENT   metier              (#PCDATA)>

<!ELEMENT   semestre            (bloc+)>
<!ATTLIST   semestre    id ID #REQUIRED>

<!ELEMENT   bloc                (ue+, role)>
<!ELEMENT   role                (#PCDATA)>

<!ELEMENT   ref-semestre        EMPTY>
<!ATTLIST   ref-semestre    ref IDREF #REQUIRED>

<!--Description usant d'un contenu mixte -->
<!ELEMENT description (#PCDATA|paragraphe|tab|liste-pucee)*>

<!ELEMENT paragraphe (#PCDATA|gras|link|italique)*>
<!ELEMENT tab (tabLine+)>
<!ELEMENT liste-pucee (paragraphe+)>

<!ELEMENT gras (#PCDATA)>
<!ELEMENT italique (#PCDATA)>
<!ELEMENT link (#PCDATA)>

<!ELEMENT tabLine (tab-element+)>
<!ELEMENT tab-element (#PCDATA)>

=== TheSmartBeaver/DPR/masterILD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Sat Feb 29 12:19:18 CET 2020 -->

<!DOCTYPE masterInformatique SYSTEM "masterILD.dtd">

<!--<masterInformatique
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="masterILD.xsd"> -->

<masterInformatique>
    <listeIntervenants>
        <intervenant id="Rem">
            <identifiant>Rem</identifiant>
            <nom>Morin Remi</nom>
            <mail> remiMorin@lis-lab.fr </mail>
            <site> remiMorin.perso.luminy@univ-amu.fr </site>
        </intervenant>

        <intervenant id="JL">
            <identifiant>Jean_Luc</identifiant>
            <nom>Jean Luc Massat</nom>
            <mail> jeanLucMassat@lis-lab.fr </mail>
            <site> jeanLucMassat.perso.luminy@univ-amu.fr </site>
            </intervenant >

        <intervenant id="EG">
            <identifiant>"Emm_G"</identifiant>
            <nom>Emmanuel Godard</nom>
            <mail> emmanuelGodard@lis-lab.fr </mail>
            <site> emmanuelGodard.perso.luminy@univ-amu.fr </site>
        </intervenant>

        <intervenant id="Nono">
            <identifiant>Noel_No</identifiant>
            <nom>Noël Novelli</nom>
            <mail> noelNovelli@lis-lab.fr </mail>
            <site> noelNovelli.perso.luminy@univ-amu.fr </site>
        </intervenant>


    </listeIntervenants>
    <parcours>
        <nom> ILD Ingénierie du logiciel et des données </nom>
        <listeResponsables>
            <responsable> Jean-Luc Massat </responsable> <responsable> Sana SELLAMI </responsable>
        </listeResponsables>
        <description>
            <paragraphe> L'objectif de ce parcours est de former des informaticiens qui soient capables à la fois de travailler </paragraphe>
            <paragraphe>sur les problématiques du développement logiciel (spécification, conception, réalisation, qualité, tests, plateforme JEE et WEB) </paragraphe>
            <paragraphe>et sur les problématiques de la modélisation et du traitement de données (administration, stockage, intégration, visualisation, analyse). </paragraphe>

            <paragraphe> Les points positifs de la formation : </paragraphe>
            <liste-pucee>
                <paragraphe> pas trop de maths mais quand même </paragraphe>
                <paragraphe> apprentissage des tests logiciels pour des applis robustes </paragraphe>
                <paragraphe> Cette formation est <gras> super </gras> avec  <italique> des profs de folie </italique>  </paragraphe>
                <paragraphe> Plus d'info sur les bénéfices de la formation sur <link> plusdinfololgg.univ-amu.fr</link></paragraphe>
            </liste-pucee>
            <tab>
                <tabLine>
                    <tab-element>M1 Info ILD</tab-element> <tab-element>M2 Info ILD</tab-element>
                </tabLine>
                <tabLine>
                    <tab-element> Des UEs communes à d'autres parcours et d'autres spécialisés ILD </tab-element>
                    <tab-element> Uniquement des UEs spécialisés ILD  </tab-element>
                </tabLine>
            </tab>
        </description>
        <listeDebouches>
            <metier>Développeur</metier>
            <metier>Ingénieur</metier>
            <metier>Assistant ingénieur</metier>
            <metier>Architecte logiciel</metier>
        </listeDebouches>
        <ref-semestre ref="S1"/>
        <ref-semestre ref="S2"/>
        <ref-semestre ref="S3ILD"/>
    </parcours>

    <semestre id="S1">
        <bloc>
            <ue >
                <nom>Reseaux</nom>
                <identifiant> Res </identifiant>
                <nbcredit>4</nbcredit>
                <lieu> Luminy;St-Jerôme;St-Charles</lieu>
                <refintervenant ref="EG"/>
            </ue>

            <ue >
                <nom>Programmation Objet Concurrente</nom>
                <identifiant> POC </identifiant>
                <nbcredit>3</nbcredit>
                <lieu> Luminy;St-Jerôme;St-Charles</lieu>
                <refintervenant ref="Rem"/>
            </ue>
            <role>UEs Obligatoires</role>
        </bloc>
    </semestre>

    <semestre id="S2">
        <bloc>
            <ue >
                <nom>Donnees P-R</nom>
                <identifiant> m1dPr </identifiant>
                <nbcredit>3</nbcredit>
                <refintervenant ref="JL"/>
            </ue>
            <ue >
                <nom>Sécurité des applications</nom>
                <identifiant> m1Secur </identifiant>
                <nbcredit>6</nbcredit>
                <refintervenant ref="JL"/>
            </ue>
            <role> UE obligatoires pour le parcours ILD </role>
        </bloc>
        <bloc>
            <ue>
                <nom>Cryptographie</nom>
                <identifiant> m1Cryp </identifiant>
                <nbcredit>3</nbcredit>
                <refintervenant ref="Rem"/>
            </ue>
            <ue >
                <nom>Interface Homme Machine</nom>
                <identifiant> IHM </identifiant>
                <nbcredit>3</nbcredit>
                <refintervenant ref="Nono"/>
            </ue>

            <role> options à choisir </role>
        </bloc>
    </semestre>

    <semestre id="S3ILD">
        <bloc>
            <ue>
                <nom>Big Data</nom>
                <identifiant>Big_D</identifiant>
                <nbcredit>6</nbcredit>
                <refintervenant ref="Nono"/>
            </ue>
            <ue >
                <nom>Génie Logiciel 2</nom>
                <identifiant>GL2</identifiant>
                <nbcredit>6</nbcredit>
                <refintervenant ref="JL"/>
            </ue>
            <role>UEs obligatoires</role>
        </bloc>
    </semestre>

</masterInformatique>
